1000="系统关机"
1001="系统即将关机。请保存所有正在进行的工作，然后注销。未保存的改动将会丢失。关机是由 %1 初始的"
1002="离关机还有 ："
1003="消息"
1004="系统关机正在进行中。\n由于 Remote Procedure Call (RPC) 服务意外终止，Windows 必须立刻重新启动。"
;1005="用法: shutdown [-i | -l | -s | -r | -a] [-f] [-m \\computername] [-t xx] [-c \"comment\"] [-d up:xx:yy]\n	没有参数		显示此消息(与 ? 相同)\n        -i			显示 GUI 界面，必须是第一个选项\n	-l			注销(不能与选项 -m 一起使用)\n	-s			关闭此计算机\n	-r			关闭并重启动此计算机\n	-a			放弃系统关机\n	-m \\computername	远程计算机关机/重启动/放弃\n	-t xx			设置关闭的超时为 xx 秒\n	-c "comment"		关闭注释(最大 127 个字符)\n	-f			强制运行的应用程序关闭而没有警告\n	-d [u][p]:xx:yy		关闭原因代码\n				u 是用户代码\n				p 是一个计划的关闭代码\n				xx 是一个主要原因代码(小于 256 的正整数)\n				yy 是一个次要原因代码(小于 65536 的正整数) "
1005="Test"